# -----------------------------------------------------
# |            Plot System - by Alps BTE
# -----------------------------------------------------
# | [Github Repo] https://github.com/AlpsBTE/PlotSystem
# | [Config Documentation] https://github.com/AlpsBTE/PlotSystem/wiki/Configuration
# | [Contacts - Discord] R3tuxn#7169, Cinnazeyy#2440
# -----------------------------------------------------

# Keep updated about newer versions
check-for-updates: true

# Enables special dev tools and features for development
# NOTE: Do not change if you do not know what you are doing
dev-mode: false

# The lobby world, where all players are teleported to, whenever they join or leave a plot
# [default] -> Uses the default multiverse spawn world
spawn-world: default

# Enable score requirement to restrict players to certain plot difficulties
# Prevents beginners from generating difficult plots
enable-score-requirement: true

# Automatic synchronisation of schematic files from SFTP/FTP servers
# [interval] -> default: 3600 seconds (1 hour)
sync-ftp-files:
  sff-enable: false
  sync-interval: 3600

# How many days of inactivity it will take before a claimed plot is automatically abandoned, -2 disables it
inactivity-interval: 14

# How many days of inactivity it will take before a rejected plots are automatically abandoned
# Use -1 to use the normal inactivity-interval, -2 disables it
rejected-inactivity-interval: -1

# Enable or disable the Group System, that allows users to invite other Builders as members of their plot,
# allowing them to build together.
# NOTE: Score will be split by all participating members
enable-group-support: true

# After how many minutes a player receives a reminder to finish his plot.
# Will be repeated every x minutes; It uses the unfinished-plots string, set it to -1 to disable
unfinished-reminder-interval: 20

# -----------------------------------------------------
# | Supported databases: MariaDB & MySQL
# -----------------------------------------------------
database:
  url: jdbc:mariadb://adress:3306/
  dbname: plotsystem
  username: plotsystem
  password: minecraft


# -----------------------------------------------------
# | Leaderboards: Shows top plot and build scores / Are placed in the spawn world
# | NOTE: Requires the HolographicDisplays plugin to work
# -----------------------------------------------------
holograms:
  # Displays the top 10 builders with the highest score
  score-leaderboard:
    sl-enable: false
    sl-x: 0
    sl-y: 0
    sl-z: 0

# Switch score-leaderboard between different time stamps
# [interval] -> default: 15 seconds
display-options:
  interval: 15
  show-daily: false
  show-weekly: true
  show-monthly: true
  show-yearly: false
  show-lifetime: false
  action-bar-enable: true
  action-bar-radius: 30


# -----------------------------------------------------
# | Formatting: Info / Alert message prefix format
# -----------------------------------------------------
chat-format:
  info-prefix: '<dark_gray>[<gold>PS</gold>] » </dark_gray>'
  alert-prefix: '<dark_gray>[<gold>PS</gold>] » </dark_gray>'


# -----------------------------------------------------
# | Shortlink: https://shlink.io/
# -----------------------------------------------------
shortlink:
  enable: false
  apikey: yourapi-key
  host: https://your.shortlink.host


# -----------------------------------------------------
# | Tutorials
# -----------------------------------------------------
tutorials:
  tutorial-enable: true
  require-beginner-tutorial: true
  tutorial-npc-name: 'Bob'
  tutorial-npc-texture: 'ewogICJ0aW1lc3RhbXAiIDogMTY0OTA0MzYzODU3MywKICAicHJvZmlsZUlkIiA6ICI5MWYwNGZlOTBmMzY0M2I1OGYyMGUzMzc1Zjg2ZDM5ZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJTdG9ybVN0b3JteSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yNzgxYjg4ZTllZGNhOGNlNWRlMzk4OTkyYzVjM2Q0NTU0ZmVkYjZmZTFiMTIzMmJkNzIwZWUyMTgyZTY4YTcyIgogICAgfQogIH0KfQ=='
  tutorial-npc-signature: 'OpazPbpK6Z+N4ehJdDORPAc+llPyczl23AEZ0aerldJUzUr15L/1yNLOmyGjo81vgjkGq5LYW43yRImtbQAg0vGHqO3u8M5PhcjKrkuezp2DTS+2nZLoN3r+mRxoUXVWWfwkOKmAzPn7TzLHGprMS6nDwJyXt0y+GQG2TYX1Wt2EsMAHSUwiLu/ykraU+JIbKEKOEaEFTRQJYZE1+I8MjA0s8cZEKokbu8LmIZRJcFvipm+pGLVioCH0z20wo7rPBNKAwDInZIsituKb/2etmaioXHadC31rkJk6PeXu3o6MFEnW20bnY5Dh9cOJQWNEM3jU4d7/DtYEBPzUaZdYoaL44jBAHC0S4pHmrIzHbGXeiSCKvhfVDtQClHtZXHVJFrjLhtW2mhVs/H5fWCah8tr9He4ogIzQ6KRME6SFOFWWmWj2A3emDlAH1lxQwPJhlig+ssuZGHPtib+4Xnq+42qwKRJKb/zmrgRzHR4LH600falI3mFpjDhKCs1hxfULrln//bMRkvb1vnNm7+Z1Zg7y5D6/3A7KNQTFASwldqQYm5dq5NC7/UBICH8Emi3qL4eqvWdFrcuH/B2lnD0rxaqVq18U3T65cGOevxl/p525p/UJSuGSP0fTOoddp/7IjCphZKL8IYVqqQjsu4tBqEQwrnaUk8hJKzGIstVUMSA='
  tutorial-chat-prefix: '<dark_gray>[<gold>Tutorial</gold>] » </dark_gray>'


# NOTE: Do not change
config-version: 3.0