# -----------------------------------------------------
# |            Plot System - by Alps BTE
# -----------------------------------------------------
# | [Github Repo] https://github.com/AlpsBTE/PlotSystem
# | [Config Documentation] https://github.com/AlpsBTE/PlotSystem/wiki/Configuration
# | [Contacts - Discord] R3tuxn#7169, Cinnazeyy#2440
# -----------------------------------------------------

# Keep updated about newer versions
check-for-updates: true

# Enables special dev tools and features for development
# NOTE: Do not change if you do not know what you are doing
dev-mode: false

# The lobby world, where all players are teleported to, whenever they join or leave a plot
# [default] -> Uses the default multiverse spawn world
spawn-world: default

# Enable score requirement to restrict players to certain plot difficulties
# Prevents beginners from generating difficult plots
enable-score-requirement: true

# Automatic synchronisation of schematic files from SFTP/FTP servers
# [interval] -> default: 3600 seconds (1 hour)
sync-ftp-files:
  enabled: false
  sync-interval: 3600

# How many days of inactivity it will take before a claimed plot is automatically abandoned
inactivity-interval: 14

# Enable or disable the Group System, that allows users to invite other Builders as members of their plot,
# allowing them to build together.
# NOTE: Score will be split by all participating members
enable-group-support: true

# -----------------------------------------------------
# | Supported databases: MariaDB & MySQL
# -----------------------------------------------------
database:
  url: jdbc:mariadb://adress:3306/
  dbname: plotsystem
  username: plotsystem
  password: minecraft


# -----------------------------------------------------
# | Leaderboards: Shows top plot and build scores / Are placed in the spawn world
# | NOTE: Requires the HolographicDisplays plugin to work
# -----------------------------------------------------
holograms:
  # Displays the top 10 builders with the highest score
  score-leaderboard:
    enabled: false
    x: 0
    y: 0
    z: 0
  # Displays the top 10 players with the most completed plots
  plots-leaderboard:
    enabled: false
    x: 0
    y: 0
    z: 0

# Switch score-leaderboard between different time stamps
# [interval] -> default: 15 seconds
display-options:
  interval: 15
  show-daily: false
  show-weekly: true
  show-monthly: true
  show-yearly: false
  show-lifetime: false
  action-bar-enabled: true
  action-bar-radius: 30


# -----------------------------------------------------
# | Navigation: The command that the player will automatically execute when pressing the navigator item in the companion
# | NOTE: Remove the "/" from whatever command you want to use
# -----------------------------------------------------
navigator:
  item: NETHER_STAR
  command: navigator


# -----------------------------------------------------
# | Formatting: Info/Error message outputs
# -----------------------------------------------------
message-prefix: §7§l>>
info-colour: §a
error-colour: §c

# -----------------------------------------------------
# | Shortlink: https://shlink.io/
# -----------------------------------------------------
shortlink:
  enable: false
  apikey: yourapi-key
  host: https://your.shortlink.host

# NOTE: Do not change
config-version: 1.7